//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelDataEntities : DbContext
    {
        public HotelDataEntities()
            : base("name=HotelDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountEmployee> AccountEmployees { get; set; }
        public virtual DbSet<AccountManager> AccountManagers { get; set; }
        public virtual DbSet<CalendarLabor> CalendarLabors { get; set; }
        public virtual DbSet<CalendarManager> CalendarManagers { get; set; }
        public virtual DbSet<CalendarReceiptor> CalendarReceiptors { get; set; }
        public virtual DbSet<Checkinout> Checkinouts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<HistoryRoomcheck> HistoryRoomchecks { get; set; }
        public virtual DbSet<InventoryAdd> InventoryAdds { get; set; }
        public virtual DbSet<InventoryHistory> InventoryHistories { get; set; }
        public virtual DbSet<InventoryTake> InventoryTakes { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Labor> Labors { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Payroll> Payrolls { get; set; }
        public virtual DbSet<Penalty> Penalties { get; set; }
        public virtual DbSet<PenaltyBoard> PenaltyBoards { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<Receiptor> Receiptors { get; set; }
        public virtual DbSet<ReportIncome> ReportIncomes { get; set; }
        public virtual DbSet<ReportInventory> ReportInventories { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<SalaryBoard> SalaryBoards { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
