//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportInventory
    {
        public string ID_ReportInventory { get; set; }
        public Nullable<decimal> Totalpriceatitems { get; set; }
        public Nullable<decimal> Totalpricedeliveritems { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        public string ID_Manager { get; set; }
    
        public virtual Manager Manager { get; set; }
    }
}
