//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public string ID_Salary { get; set; }
        public string ID_Employee { get; set; }
        public string ID_SalaryBoard { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        public string Shift { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SalaryBoard SalaryBoard { get; set; }
    }
}
